version: '2'
services:
  web.com:
    build: .
    command: bash -c "./compose/start.sh"
    ports:
        - "8000:8000"
    volumes:
      - .:/app/
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    ports:
        - "5433:5432"
    volumes:
      - /var/lib/postgresql/data
